Overlay with explaination added
komodorio/helm-dashboard pull request #120
Opened 2022-11-28 05:56 UTC by siddhikhapare

2022-11-28 20:30 UTC, undera commented on pkg/dashboard/static/index.html
> +            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#Modal">
Let's keep the original button, the purpose of the issue were only to add the modal. Attaching the handler to `i.bi-power` would work just fine

2022-11-28 21:02 UTC, undera requested changes
Please address my comments

2022-11-29 06:24 UTC, hdm23061993 commented
Fixes #105

2022-11-29 09:13 UTC, siddhikhapare commented
Sure @undera

2022-11-29 10:15 UTC, closed without merging