Create an empty global modal
komodorio/helm-dashboard pull request #253
Opened 2023-03-13 23:32 UTC by ErezBiren

## Changes Proposed

Related to Issue #243 
I opened a Draft pull request just for code review, it's not the final PR.
I would love to get some feedback, to make sure I took the right path.

I've created an empty modal that takes as arguments:
title text, content text, and an array of actions.
each action will be translated to a button at the bottom of the modal.
each action includes a string, a callback, and a style.

## UI image from Storybook

![image](https://user-images.githubusercontent.com/7828909/224851664-b6d1540b-4b5c-428b-8a1a-208fe1801619.png)

## Check List

- [x] The title of my pull request is a short description of the changes
- [x] This PR relates to some issue: 
- [ ] I have documented the changes made (if applicable)
- [ ] I have covered the changes with unit tests
- [ ] The Modal Title can be fully customized instead of just text.
- [ ] The Modal Content can be fully customized instead of just text.
- [ ] Track multiple open modals.
- [ ] The middle section should expand according to the content displayed up to the size of 500px after that a scroll wheel should appear.

2023-03-14 11:53 UTC, chad11111 commented
@ErezBiren I think u carried over unwanted changes (probably from main)

2023-03-14 12:23 UTC, ErezBiren commented
@chad11111 
Yes, I've noticed that but wasn't sure about it.
I'll try to get rid of them and do a new PR

2023-03-17 03:24 UTC, chad11111 requested changes

2023-03-17 03:24 UTC, chad11111 commented on dashboard/src/components/modal/Modal.stories.tsx
> +import { ComponentStory, ComponentMeta } from "@storybook/react";
I wasn't able to get the storybook running.

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/127234894/225804985-c7dd9ab1-0ac3-49d0-9075-9fd6867c60b5.png">

2023-03-17 03:24 UTC, chad11111 commented on dashboard/src/components/modal/Modal.stories.tsx
> +import { ComponentStory, ComponentMeta } from "@storybook/react";
@ErezBiren other then that amazing job!

2023-03-18 20:21 UTC, merged