skeleton for helm-dashboard-v2
komodorio/helm-dashboard pull request #266
Opened 2023-03-15 17:10 UTC by aman1376

## Changes Proposed

Created the skeleton for the dashboard with mock data

![Screenshot (51)](https://user-images.githubusercontent.com/96187306/225387010-815dd83e-ecd8-4347-8c64-1c18b81bbf20.png)

## Check List

- [ x] The title of my pull request is a short description of the changes
- [x ] This PR relates to some issue: 
- [ x] I have documented the changes made (if applicable)
- [ ] I have covered the changes with unit tests

2023-03-15 17:12 UTC, aman1376 commented
@chad11111 please have a look at this.

2023-03-17 03:27 UTC, chad11111 requested changes

2023-03-17 03:27 UTC, chad11111 commented on dashboard/src/App.tsx
> +    //       </a>
remove the commented code plz.

2023-03-17 03:27 UTC, chad11111 commented on go.sum
> +cloud.google.com/go v0.84.0/go.mod h1:RazrYuxIK6Kb7YrzzhPoLmCVzl7Sup4NrbKPg8KHSUM=
plz remove this from the pr.

2023-03-17 03:27 UTC, chad11111 commented on dashboard/src/App.tsx
> +    <div className="app">
please break these into separate smaller components like header, body, etc...

2023-03-17 03:32 UTC, chad11111 commented on go.sum
> +cloud.google.com/go v0.84.0/go.mod h1:RazrYuxIK6Kb7YrzzhPoLmCVzl7Sup4NrbKPg8KHSUM=
im guessing the test is failing because of this.

2023-03-17 14:49 UTC, aman1376 commented
@chad11111 made the changes please have a look

2023-03-18 22:47 UTC, chad11111 commented on dashboard/src/layout/Body.tsx
> +          <Body_header/>
Please use camel case `BodyHeader`

2023-03-18 22:49 UTC, merged