Repo_Manage_Section_UI
komodorio/helm-dashboard pull request #272
Opened 2023-03-18 13:03 UTC by aman1376

## Changes Proposed

Created the UI for repository manage section

![Screenshot (54)](https://user-images.githubusercontent.com/96187306/226107971-f263e9e2-611f-45be-b108-531577dc8081.png)

## Check List

- [X] The title of my pull request is a short description of the changes
- [X] This PR relates to some issue: 
- [X] I have documented the changes made (if applicable)
- [ ] I have covered the changes with unit tests

2023-03-18 13:04 UTC, aman1376 commented
@chad11111 please have a look.

2023-03-18 20:34 UTC, chad11111 commented on dashboard/src/Repo_Manage_Section.css
> +}
```suggestion
}

```

2023-03-18 20:36 UTC, chad11111 requested changes

2023-03-18 20:36 UTC, chad11111 commented on dashboard/src/Repo_Manage_Section.tsx
> +function Repo_Manage_Section():JSX.Element {
please rename this to `RepoManageSection`

2023-03-18 20:36 UTC, chad11111 commented on dashboard/src/App.tsx
> +    <Repo_Manage_Section/>
remove the changes here

2023-03-19 03:28 UTC, chad11111 commented
@aman1376 Please don't snake case (Repo_Manage_Section) only camel case (RepoManageSection)

2023-03-19 03:28 UTC, chad11111 commented
@aman1376 also please fix conflicts

2023-03-20 12:25 UTC, chad11111 commented
@aman1376 why did u close it ?

2023-03-20 12:26 UTC, aman1376 commented
i have created a new pull request RepoManageSection

2023-03-20 12:27 UTC, closed without merging