React query integration
komodorio/helm-dashboard pull request #345
Opened 2023-04-17 18:45 UTC by ErezBiren

Add a lot of new API requests
@chad11111

2023-04-18 00:48 UTC, ImmanuelSegol commented on dashboard/src/components/InstalledPackages/InstalledPackageCard.tsx
> +    console.log(release)
remove

2023-04-18 00:49 UTC, ImmanuelSegol commented on dashboard/src/components/revision/RevisionDetails.tsx
> +  console.log("111" + JSON.stringify(release));
remove

2023-04-18 00:49 UTC, ImmanuelSegol commented on dashboard/src/components/revision/RevisionDetails.tsx
> +    console.error("not implemented");
throw an error no?

2023-04-19 06:59 UTC, ErezBiren commented
@chad11111

2023-04-19 21:50 UTC, chad11111 commented on dashboard/src/components/InstalledPackages/InstalledPackageCard.tsx
> +    console.log(release);
remove plz

2023-04-19 21:50 UTC, chad11111 requested changes

2023-04-19 21:50 UTC, chad11111 commented on dashboard/src/components/revision/RevisionsList.tsx
> +  releaseRevisions: ReleaseRevision[] | undefined;
just use ?

2023-04-21 16:28 UTC, ErezBiren commented on dashboard/src/components/revision/RevisionsList.tsx
> +  releaseRevisions: ReleaseRevision[] | undefined;
done

2023-04-21 16:28 UTC, ErezBiren commented on dashboard/src/components/InstalledPackages/InstalledPackageCard.tsx
> +    console.log(release);
done

2023-05-02 17:28 UTC, merged