Helm dashboard v2
komodorio/helm-dashboard pull request #402
Opened 2023-06-27 13:55 UTC by dav-sap

## Changes Proposed

## Check List

- [ ] The title of my pull request is a short description of the changes
- [ ] This PR relates to some issue: 
- [ ] I have documented the changes made (if applicable)
- [ ] I have covered the changes with unit tests

2023-06-27 16:46 UTC, chad11111 requested changes

2023-06-27 16:46 UTC, chad11111 commented on dashboard/src/API/apiService.ts
> -if (import.meta.env.DEV) {
plz make the `http://localhost:8080` an env

2023-06-27 17:20 UTC, undera commented on dashboard/src/API/apiService.ts
> -let baseURL = "";
I'm not sure why this code is deleted. It used to work well to support both local dev work and production setup. @nir2002

2023-06-28 19:56 UTC, chad11111 approved these changes

2023-06-29 21:29 UTC, merged